import type { NextPage } from 'next'
import Link from 'next/link'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

import useAddrStore, { MyStateR } from '../context/contextGlobal/contextGlobal'

import { useEffect, useState } from 'react'

import { Box } from '@chakra-ui/react'
import { Stack, HStack, VStack, StackDivider } from '@chakra-ui/react'
import { Center, Square, Circle } from '@chakra-ui/react'
import { Button, ButtonGroup } from '@chakra-ui/react'
import ButtonLL, { LLprops, WhoParent } from '../component/ButtonLL'
import { Text } from '@chakra-ui/react'

const Home: NextPage = () => {
  const adParent = useAddrStore(state => state.AddressParent);
  const [myAdParent, setmyAdParent] = useState<bigint>();
  useEffect(() => { setmyAdParent(adParent) }, [adParent]);

  return (
    <>
      <Box bg="gray.200" w='100%' color='gray.800' borderWidth='1px' overflow='hidden'>
        <Center>
          <HStack spacing={4}>

            <ButtonLL genderPerson={WhoParent.father} />
            <ButtonLL genderPerson={WhoParent.mother} />

          </HStack>
        </Center>
        <Text>Addr Parent = {String(myAdParent)}  </Text>
      </Box>
      <Box h={10}></Box>
      <VStack spacing={10} divider={<StackDivider borderColor='gray.400' />}>

        <Link href='parentInterface'>
          <Button colorScheme='facebook' >
            Parent interface
          </Button >
        </Link>
        <Button colorScheme='facebook' >
          Children interface
        </Button ><Button colorScheme='facebook' >
          Game interface
        </Button >


      </VStack>
    </>
    //       This is it. 🚧

    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js🚧!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
